apiVersion: v1
kind: ServiceAccount
metadata:
  name: bm-photo
  namespace: bm-photo
  labels:
    app.kubernetes.io/name: bm-photo
---
apiVersion: v1
kind: Service
metadata:
  name: bm-photo
  namespace: bm-photo
  labels:
    app.kubernetes.io/name: bm-photo
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: bm-photo
    app.kubernetes.io/component: app
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bm-photo-pdb
  namespace: bm-photo
  labels:
    app.kubernetes.io/name: bm-photo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bm-photo
